fos_js_routing:
    routes_to_expose:
        # Homepage
        - public_app_homepage

        # Product
        - shop_product_list

        # Registration
        - user_registration_register

        # Security
        - user_security_login
        - user_security_logout

        # Product
        - shop_product_products_list
        - shop_product_list
        - shop_product_show
        - admin_shop_product_list
        - admin_shop_product_new
        - admin_shop_product_edit
        - admin_shop_product_delete

        # Category
        - shop_category_categories_list
        - shop_category_list
        - admin_shop_category_list
        - admin_shop_category_new
        - admin_shop_category_edit
        - admin_shop_category_delete

        # User
        - public_user_user_show

        # Cart
        - shop_cart_show
        - shop_cart_list
        - shop_cart_new
        - shop_cart_edit

        # Cart Item
        - shop_cart_item_list
        - shop_cart_item_new
        - shop_cart_item_edit
        - shop_cart_item_delete

        # Order
        - shop_order_list
        - shop_order_show
        - shop_order_show_history
        - shop_order_new
        - shop_order_edit
        - shop_order_delete

        # OrderItem
        - shop_order_item_list
        - shop_order_item_new
        - shop_order_item_edit
        - shop_order_item_delete

        # Shipping
        - shop_shipping_shipping_list
        - shop_shipping_list
        - shop_shipping_new
        - shop_shipping_edit

        # Billing
        - shop_billing_list
        - shop_billing_new
        - shop_billing_edit

        # Stripe
        - shop_stripe_new

        # Payment
        - shop_payment_new
        - shop_payment_edit
        - shop_payment_delete

        # Delivery
        - shop_delivery_list

        # Wishlist
        - shop_wishlist_show
        - shop_wishlist_list
        - shop_wishlist_new
        - shop_wishlist_edit

        # WishlistItem
        - shop_wishlist_item_list
        - shop_wishlist_item_new
        - shop_wishlist_item_edit
        - shop_wishlist_item_delete
