app:
    resource: "@AppBundle/Resources/config/routing.yaml"
    prefix: /

shop:
    resource: "@ShopBundle/Resources/config/routing.yaml"
    prefix: /

user:
    resource: "@UserBundle/Resources/config/routing.yaml"
    prefix: /
