
shop_billing_user_billings_list:
    path: /api/user/{id}/billings
    controller: ShopBundle\Controller\BillingController::userBillingsListAction
    methods: GET

shop_billing_new:
    path: /api/billing/new
    controller: ShopBundle\Controller\BillingController::newAction
    methods: POST

shop_billing_edit:
    path: /api/billing/{id}/edit
    controller: ShopBundle\Controller\BillingController::editAction
    methods: PUT
