shop_cart_show:
    path: /cart
    controller: ShopBundle\Controller\CartController::showAction
    methods: GET

shop_cart_list:
    path: /user/{id}/cart
    controller: ShopBundle\Controller\CartController::listAction
    methods: GET

shop_cart_new:
    path: /cart/new
    controller: ShopBundle\Controller\CartController::newAction
    methods: POST

shop_cart_edit:
    path: /cart/{id}/edit
    controller: ShopBundle\Controller\CartController::editAction
    methods: PUT

shop_cart_delete:
    path: /cart/{id}/delete
    controller: ShopBundle\Controller\CartController::deleteAction
    methods: DELETE
