
shop_order_item_list:
    path: /order/{id}/orderItems
    controller: ShopBundle\Controller\OrderItemController::listAction
    methods: GET

shop_order_item_new:
    path: /orderItem/new
    controller: ShopBundle\Controller\OrderItemController::newAction
    methods: POST

shop_order_item_edit:
    path: /orderItem/{id}/edit
    controller: ShopBundle\Controller\OrderItemController::editAction
    methods: PUT

shop_order_item_delete:
    path: /orderItem/{id}/delete
    controller: ShopBundle\Controller\OrderItemController::deleteAction
    methods: DELETE
