
shop_wishlist_item_list:
    path: /wishlist/{id}/wishlistItems
    controller: ShopBundle\Controller\WishlistItemController::listAction
    methods: GET

shop_wishlist_item_new:
    path: /wishlistItem/new
    controller: ShopBundle\Controller\WishlistItemController::newAction
    methods: POST

shop_wishlist_item_edit:
    path: /wishlistItem/{id}/edit
    controller: ShopBundle\Controller\WishlistItemController::editAction
    methods: PUT

shop_wishlist_item_delete:
    path: /wishlistItem/{id}/delete
    controller: ShopBundle\Controller\WishlistItemController::deleteAction
    methods: DELETE
