
shop_wishlist_show:
    path: /wishlist
    controller: ShopBundle\Controller\WishlistController::showAction
    methods: GET

shop_wishlist_list:
    path: user/{id}/wishlist
    controller: ShopBundle\Controller\WishlistController::listAction
    methods: GET

shop_wishlist_new:
    path: /wishlist/new
    controller: ShopBundle\Controller\WishlistController::newAction
    methods: POST

shop_wishlist_edit:
    path: /wishlist/{id}/edit
    controller: ShopBundle\Controller\WishlistController::editAction
    methods: PUT
